package br.com.fiap.geoworldmania.repository

import br.com.fiap.geoworldmania.R
import br.com.fiap.geoworldmania.model.FlagSvg
import br.com.fiap.geoworldmania.model.Nome
import br.com.fiap.geoworldmania.model.Pais
import br.com.fiap.geoworldmania.model.Portugues

fun getAllPaises(): List<Pais> {
    return listOf(
        Pais(nome=Portugues(portugues=Nome(common="Chipre")), capital=listOf("Nicósia"), bandeira=FlagSvg(png=R.drawable.cy), regiao="Europa", sigla="CY"),
        Pais(nome=Portugues(portugues=Nome(common="Eritreia")), capital=listOf("Asmara"), bandeira=FlagSvg(png=R.drawable.er), regiao="Africa", sigla="ER"),
        Pais(nome=Portugues(portugues=Nome(common="Libéria")), capital=listOf("Monróvia"), bandeira=FlagSvg(png=R.drawable.lr), regiao="Africa", sigla="LR"),
        Pais(nome=Portugues(portugues=Nome(common="Bermudas")), capital=listOf("Hamilton"), bandeira=FlagSvg(png=R.drawable.bm), regiao="America do Norte e Central", sigla="BM"),
        Pais(nome=Portugues(portugues=Nome(common="Cidade do Vaticano")), capital=listOf("Cidade do Vaticano"), bandeira=FlagSvg(png=R.drawable.va), regiao="Europa", sigla="VA"),
        Pais(nome=Portugues(portugues=Nome(common="Ilhas Cook")), capital=listOf("Avarua"), bandeira=FlagSvg(png=R.drawable.ck), regiao="Oceania", sigla="CK"),
        Pais(nome=Portugues(portugues=Nome(common="Somália")), capital=listOf("Mogadíscio"), bandeira=FlagSvg(png=R.drawable.so), regiao="Africa", sigla="SO"),
        Pais(nome=Portugues(portugues=Nome(common="Zâmbia")), capital=listOf("Lusaka"), bandeira=FlagSvg(png=R.drawable.zm), regiao="Africa", sigla="ZM"),
        Pais(nome=Portugues(portugues=Nome(common="Venezuela")), capital=listOf("Caracas"), bandeira=FlagSvg(png=R.drawable.ve), regiao="America do Sul", sigla="VE"),
        Pais(nome=Portugues(portugues=Nome(common="Turquemenistão")), capital=listOf("Asgabate"), bandeira=FlagSvg(png=R.drawable.tm), regiao="Asia", sigla="TM"),
        Pais(nome=Portugues(portugues=Nome(common="Albânia")), capital=listOf("Tirana"), bandeira=FlagSvg(png=R.drawable.al), regiao="Europa", sigla="AL"),
        Pais(nome=Portugues(portugues=Nome(common="Croácia")), capital=listOf("Zagreb"), bandeira=FlagSvg(png=R.drawable.hr), regiao="Europa", sigla="HR"),
        Pais(nome=Portugues(portugues=Nome(common="Reino Unido")), capital=listOf("Londres"), bandeira=FlagSvg(png=R.drawable.gb), regiao="Europa", sigla="GB"),
        Pais(nome=Portugues(portugues=Nome(common="Sudão")), capital=listOf("Cartum"), bandeira=FlagSvg(png=R.drawable.sd), regiao="Africa", sigla="SD"),
        Pais(nome=Portugues(portugues=Nome(common="Timor-Leste")), capital=listOf("Díli"), bandeira=FlagSvg(png=R.drawable.tl), regiao="Asia", sigla="TL"),
        Pais(nome=Portugues(portugues=Nome(common="Congo")), capital=listOf("Brazzaville"), bandeira=FlagSvg(png=R.drawable.cg), regiao="Africa", sigla="CG"),
        Pais(nome=Portugues(portugues=Nome(common="Azerbeijão")), capital=listOf("Baku"), bandeira=FlagSvg(png=R.drawable.az), regiao="Asia", sigla="AZ"),
        Pais(nome=Portugues(portugues=Nome(common="Quénia")), capital=listOf("Nairóbi"), bandeira=FlagSvg(png=R.drawable.ke), regiao="Africa", sigla="KE"),
        Pais(nome=Portugues(portugues=Nome(common="Samoa Americana")), capital=listOf("Pago Pago"), bandeira=FlagSvg(png=R.drawable.`as`), regiao="Oceania", sigla="AS"),
        Pais(nome=Portugues(portugues=Nome(common="Costa do Marfim")), capital=listOf("Yamussucro"), bandeira=FlagSvg(png=R.drawable.ci), regiao="Africa", sigla="CI"),
        Pais(nome=Portugues(portugues=Nome(common="Senegal")), capital=listOf("Dakar"), bandeira=FlagSvg(png=R.drawable.sn), regiao="Africa", sigla="SN"),
        Pais(nome=Portugues(portugues=Nome(common="Vietname")), capital=listOf("Hanói"), bandeira=FlagSvg(png=R.drawable.vn), regiao="Asia", sigla="VN"),
        Pais(nome=Portugues(portugues=Nome(common="El Salvador")), capital=listOf("São Salvador"), bandeira=FlagSvg(png=R.drawable.sv), regiao="America do Norte e Central", sigla="SV"),
        Pais(nome=Portugues(portugues=Nome(common="Afeganistão")), capital=listOf("Kabul"), bandeira=FlagSvg(png=R.drawable.af), regiao="Asia", sigla="AF"),
        Pais(nome=Portugues(portugues=Nome(common="São Martinho")), capital=listOf("Marigot"), bandeira=FlagSvg(png=R.drawable.mf), regiao="America do Norte e Central", sigla="FM"),
        Pais(nome=Portugues(portugues=Nome(common="Letónia")), capital=listOf("Riga"), bandeira=FlagSvg(png=R.drawable.lv), regiao="Europa", sigla="LV"),
        Pais(nome=Portugues(portugues=Nome(common="Guatemala")), capital=listOf("Cidade da Guatemala"), bandeira=FlagSvg(png=R.drawable.gt), regiao="America do Norte e Central", sigla="GT"),
        Pais(nome=Portugues(portugues=Nome(common="Kuwait")), capital=listOf("Cidade do Kuwait"), bandeira=FlagSvg(png=R.drawable.kw), regiao="Asia", sigla="KW"),
        Pais(nome=Portugues(portugues=Nome(common="São Tomé e Príncipe")), capital=listOf("São Tomé"), bandeira=FlagSvg(png=R.drawable.st), regiao="Ámérica", sigla="ST"),
        Pais(nome=Portugues(portugues=Nome(common="Quirguistão")), capital=listOf("Bishkek"), bandeira=FlagSvg(png=R.drawable.kg), regiao="Asia", sigla="KG"),
        Pais(nome=Portugues(portugues=Nome(common="Polónia")), capital=listOf("Varsóvia"), bandeira=FlagSvg(png=R.drawable.pl), regiao="Europa", sigla="PL"),
        Pais(nome=Portugues(portugues=Nome(common="Guam")), capital=listOf("Hagåtña"), bandeira=FlagSvg(png=R.drawable.gu), regiao="Oceania", sigla="GU"),
        Pais(nome=Portugues(portugues=Nome(common="Gana")), capital=listOf("Acra"), bandeira=FlagSvg(png=R.drawable.gh), regiao="Africa", sigla="GH"),
        Pais(nome=Portugues(portugues=Nome(common="Lituânia")), capital=listOf("Vilnius"), bandeira=FlagSvg(png=R.drawable.lt), regiao="Europa", sigla="LT"),
        Pais(nome=Portugues(portugues=Nome(common="Arménia")), capital=listOf("Yerevan"), bandeira=FlagSvg(png=R.drawable.am), regiao="Asia", sigla="AM"),
        Pais(nome=Portugues(portugues=Nome(common="Jersey")), capital=listOf("Saint Helier"), bandeira=FlagSvg(png=R.drawable.je), regiao="Europa", sigla="J.E"),
        Pais(nome=Portugues(portugues=Nome(common="Granada")), capital=listOf("St. George's"), bandeira=FlagSvg(png=R.drawable.gd), regiao="America do Norte e Central", sigla="GD"),
        Pais(nome=Portugues(portugues=Nome(common="Tajiquistão")), capital=listOf("Dushanbe"), bandeira=FlagSvg(png=R.drawable.tj), regiao="Asia", sigla="TJ"),
        Pais(nome=Portugues(portugues=Nome(common="Etiópia")), capital=listOf("Addis Abeba"), bandeira=FlagSvg(png=R.drawable.et), regiao="Africa", sigla="ET"),
        Pais(nome=Portugues(portugues=Nome(common="Saara Ocidental")), capital=listOf("El Aaiún"), bandeira=FlagSvg(png=R.drawable.eh), regiao="Africa", sigla="EH"),
        Pais(nome=Portugues(portugues=Nome(common="Marrocos")), capital=listOf("Rabat"), bandeira=FlagSvg(png=R.drawable.ma), regiao="Africa", sigla="MA"),
        Pais(nome=Portugues(portugues=Nome(common="Porto Rico")), capital=listOf("San Juan"), bandeira=FlagSvg(png=R.drawable.pr), regiao="America do Norte e Central", sigla="RP"),
        Pais(nome=Portugues(portugues=Nome(common="Ilha do Natal")), capital=listOf("Flying Fish Cove"), bandeira=FlagSvg(png=R.drawable.cx), regiao="Oceania", sigla="CX"),
        Pais(nome=Portugues(portugues=Nome(common="Nova Zelândia")), capital=listOf("Wellington"), bandeira=FlagSvg(png=R.drawable.nz), regiao="Oceania", sigla="NZ"),
        Pais(nome=Portugues(portugues=Nome(common="Brunei")), capital=listOf("Bandar Seri Begawan"), bandeira=FlagSvg(png=R.drawable.bn), regiao="Asia", sigla="BN"),
        Pais(nome=Portugues(portugues=Nome(common="Guiana Francesa")), capital=listOf("Caiena"), bandeira=FlagSvg(png=R.drawable.gf), regiao="America do Sul", sigla="GF"),
        Pais(nome=Portugues(portugues=Nome(common="Niue")), capital=listOf("Alofi"), bandeira=FlagSvg(png=R.drawable.nu), regiao="Oceania", sigla="NU"),
        Pais(nome=Portugues(portugues=Nome(common="Roménia")), capital=listOf("Bucareste"), bandeira=FlagSvg(png=R.drawable.ro), regiao="Europa", sigla="RO"),
        Pais(nome=Portugues(portugues=Nome(common="Ilhas Svalbard e Jan Mayen")), capital=listOf("Longyearbyen"), bandeira=FlagSvg(png=R.drawable.sj), regiao="Europa", sigla="SJ"),
        Pais(nome=Portugues(portugues=Nome(common="Bielorússia")), capital=listOf("Minsk"), bandeira=FlagSvg(png=R.drawable.by), regiao="Europa", sigla="BY"),
        Pais(nome=Portugues(portugues=Nome(common="Panamá")), capital=listOf("Cidade do Panamá"), bandeira=FlagSvg(png=R.drawable.pa), regiao="America do Norte e Central", sigla="PA"),
        Pais(nome=Portugues(portugues=Nome(common="Camarões")), capital=listOf("Yaoundé"), bandeira=FlagSvg(png=R.drawable.cm), regiao="Africa", sigla="CM"),
        Pais(nome=Portugues(portugues=Nome(common="Chéquia")), capital=listOf("Praga"), bandeira=FlagSvg(png=R.drawable.cz), regiao="Europa", sigla="CZ"),
        Pais(nome=Portugues(portugues=Nome(common="São Bartolomeu")), capital=listOf("Gustavia"), bandeira=FlagSvg(png=R.drawable.bl), regiao="America do Norte e Central", sigla="BL"),
        Pais(nome=Portugues(portugues=Nome(common="Grécia")), capital=listOf("Atenas"), bandeira=FlagSvg(png=R.drawable.gr), regiao="Europa", sigla="GR"),
        Pais(nome=Portugues(portugues=Nome(common="Mali")), capital=listOf("Bamako"), bandeira=FlagSvg(png=R.drawable.ml), regiao="Africa", sigla="ML"),
        Pais(nome=Portugues(portugues=Nome(common="Martinica")), capital=listOf("Fort-de-France"), bandeira=FlagSvg(png=R.drawable.mq), regiao="America do Norte e Central", sigla="MQ"),
        Pais(nome=Portugues(portugues=Nome(common="França")), capital=listOf("Paris"), bandeira=FlagSvg(png=R.drawable.fr), regiao="Europa", sigla="FR"),
        Pais(nome=Portugues(portugues=Nome(common="Paquistão")), capital=listOf("Islamabad"), bandeira=FlagSvg(png=R.drawable.pk), regiao="Asia", sigla="PK"),
        Pais(nome=Portugues(portugues=Nome(common="Perú")), capital=listOf("Lima"), bandeira=FlagSvg(png=R.drawable.pe), regiao="America do Sul", sigla="PE"),
        Pais(nome=Portugues(portugues=Nome(common="Barbados")), capital=listOf("Bridgetown"), bandeira=FlagSvg(png=R.drawable.bb), regiao="America do Norte e Central", sigla="BB"),
        Pais(nome=Portugues(portugues=Nome(common="Gronelândia")), capital=listOf("Nuuk"), bandeira=FlagSvg(png=R.drawable.gl), regiao="America do Norte e Central", sigla="GL"),
        Pais(nome=Portugues(portugues=Nome(common="Saint-Pierre e Miquelon")), capital=listOf("Saint-Pierre"), bandeira=FlagSvg(png=R.drawable.pm), regiao="America do Norte e Central", sigla="PM"),
        Pais(nome=Portugues(portugues=Nome(common="Chade")), capital=listOf("Djamena"), bandeira=FlagSvg(png=R.drawable.td), regiao="Africa", sigla="TD"),
        Pais(nome=Portugues(portugues=Nome(common="Hungria")), capital=listOf("Budapeste"), bandeira=FlagSvg(png=R.drawable.hu), regiao="Europa", sigla="HU"),
        Pais(nome=Portugues(portugues=Nome(common="Comores")), capital=listOf("Moroni"), bandeira=FlagSvg(png=R.drawable.km), regiao="Africa", sigla="KM"),
        Pais(nome=Portugues(portugues=Nome(common="Bangladesh")), capital=listOf("Dhaka"), bandeira=FlagSvg(png=R.drawable.bd), regiao="Asia", sigla="BD"),
        Pais(nome=Portugues(portugues=Nome(common="Tokelau")), capital=listOf("Fakaofo"), bandeira=FlagSvg(png=R.drawable.tk), regiao="Oceania", sigla="TK"),
        Pais(nome=Portugues(portugues=Nome(common="Fiji")), capital=listOf("Suva"), bandeira=FlagSvg(png=R.drawable.fj), regiao="Oceania", sigla="FJ"),
        Pais(nome=Portugues(portugues=Nome(common="China")), capital=listOf("Beijing"), bandeira=FlagSvg(png=R.drawable.cn), regiao="Asia", sigla="CN"),
        Pais(nome=Portugues(portugues=Nome(common="Colômbia")), capital=listOf("Bogotá"), bandeira=FlagSvg(png=R.drawable.co), regiao="America do Sul", sigla="CO"),
        Pais(nome=Portugues(portugues=Nome(common="Ilhas Virgens")), capital=listOf("Road Town"), bandeira=FlagSvg(png=R.drawable.vg), regiao="America do Norte e Central", sigla="VG"),
        Pais(nome=Portugues(portugues=Nome(common="Argélia")), capital=listOf("Argel"), bandeira=FlagSvg(png=R.drawable.dz), regiao="Africa", sigla="DZ"),
        Pais(nome=Portugues(portugues=Nome(common="Maldivas")), capital=listOf("Malé"), bandeira=FlagSvg(png=R.drawable.mv), regiao="Asia", sigla="MV"),
        Pais(nome=Portugues(portugues=Nome(common="MalAsia")), capital=listOf("Kuala Lumpur"), bandeira=FlagSvg(png=R.drawable.my), regiao="Asia", sigla="MEU"),
        Pais(nome=Portugues(portugues=Nome(common="Ilhas Caimão")), capital=listOf("George Town"), bandeira=FlagSvg(png=R.drawable.ky), regiao="America do Norte e Central", sigla="KY"),
        Pais(nome=Portugues(portugues=Nome(common="Espanha")), capital=listOf("Madrid"), bandeira=FlagSvg(png=R.drawable.es), regiao="Europa", sigla="ES"),
        Pais(nome=Portugues(portugues=Nome(common="Irlanda")), capital=listOf("Dublin"), bandeira=FlagSvg(png=R.drawable.ie), regiao="Europa", sigla="IE"),
        Pais(nome=Portugues(portugues=Nome(common="Estónia")), capital=listOf("Tallinn"), bandeira=FlagSvg(png=R.drawable.ee), regiao="Europa", sigla="EE"),
        Pais(nome=Portugues(portugues=Nome(common="Paraguai")), capital=listOf("Assunção"), bandeira=FlagSvg(png=R.drawable.py), regiao="America do Sul", sigla="PY"),
        Pais(nome=Portugues(portugues=Nome(common="Uruguai")), capital=listOf("Montevideo"), bandeira=FlagSvg(png=R.drawable.uy), regiao="America do Sul", sigla="UY"),
        Pais(nome=Portugues(portugues=Nome(common="Africa do Sul")), capital=listOf("Pretória, Bloemfontein, Cidade do Cabo"), bandeira=FlagSvg(png=R.drawable.za), regiao=" Africa", sigla="ZA"),
        Pais(nome=Portugues(portugues=Nome(common="Santa Lúcia")), capital=listOf("Castries"), bandeira=FlagSvg(png=R.drawable.lc), regiao="America do Norte e Central", sigla="LC"),
        Pais(nome=Portugues(portugues=Nome(common="Vanuatu")), capital=listOf("Port Vila"), bandeira=FlagSvg(png=R.drawable.vu), regiao="Oceania", sigla="VU"),
        Pais(nome=Portugues(portugues=Nome(common="Finlândia")), capital=listOf("Helsinque"), bandeira=FlagSvg(png=R.drawable.fi), regiao="Europa", sigla="FI"),
        Pais(nome=Portugues(portugues=Nome(common="Suécia")), capital=listOf("Estocolmo"), bandeira=FlagSvg(png=R.drawable.se), regiao="Europa", sigla="SE"),
        Pais(nome=Portugues(portugues=Nome(common="Território Britânico do Oceano Índico")), capital=listOf("Diego Garcia"), bandeira=FlagSvg(png=R.drawable.io), regiao="Africa" , sigla="IO"),
        Pais(nome=Portugues(portugues=Nome(common="Líbano")), capital=listOf("Beirute"), bandeira=FlagSvg(png=R.drawable.lb), regiao="Asia", sigla="LB"),
        Pais(nome=Portugues(portugues=Nome(common="Estados Unidos")), capital=listOf("Washington, D.C."), bandeira=FlagSvg(png=R.drawable.us), regiao="America do Norte e Central", sigla="US"),
        Pais(nome=Portugues(portugues=Nome(common="Chile")), capital=listOf("Santiago"), bandeira=FlagSvg(png=R.drawable.cl), regiao="America do Sul", sigla="CL"),
        Pais(nome=Portugues(portugues=Nome(common="Ilha Norfolk")), capital=listOf("Kingston"), bandeira=FlagSvg(png=R.drawable.nf), regiao="Oceania", sigla="NF"),
        Pais(nome=Portugues(portugues=Nome(common="Montserrat")), capital=listOf("Plymouth"), bandeira=FlagSvg(png=R.drawable.ms), regiao="America do Norte e Central", sigla="MS"),
        Pais(nome=Portugues(portugues=Nome(common="Austrália")), capital=listOf("Canberra"), bandeira=FlagSvg(png=R.drawable.au), regiao="Oceania", sigla="AU"),
        Pais(nome=Portugues(portugues=Nome(common="Belize")), capital=listOf("Belmopan"), bandeira=FlagSvg(png=R.drawable.bz), regiao="America do Norte e Central", sigla="BZ"),
        Pais(nome=Portugues(portugues=Nome(common="Guiana")), capital=listOf("Georgetown"), bandeira=FlagSvg(png=R.drawable.gy), regiao="America do Sul", sigla="GY"),
        Pais(nome=Portugues(portugues=Nome(common="Mongólia")), capital=listOf("Ulan Bator"), bandeira=FlagSvg(png=R.drawable.mn), regiao="Asia", sigla="MN"),
        Pais(nome=Portugues(portugues=Nome(common="Tuvalu")), capital=listOf("Funafuti"), bandeira=FlagSvg(png=R.drawable.tv), regiao="Oceania", sigla="TV"),
        Pais(nome=Portugues(portugues=Nome(common="República Dominicana")), capital=listOf("Santo Domingo"), bandeira=FlagSvg(png=R.drawable.doo), regiao="America do Norte e Central", sigla="DOO"),
        Pais(nome=Portugues(portugues=Nome(common="Guiné Equatorial")), capital=listOf("Malabo"), bandeira=FlagSvg(png=R.drawable.gq), regiao="Africa", sigla="QG"),
        Pais(nome=Portugues(portugues=Nome(common="São Cristóvão e Nevis")), capital=listOf("Basseterre"), bandeira=FlagSvg(png=R.drawable.kn), regiao="America do Norte e Central", sigla="KN"),
        Pais(nome=Portugues(portugues=Nome(common="Bolívia")), capital=listOf("Sucre"), bandeira=FlagSvg(png=R.drawable.bo), regiao="America do Sul", sigla="BO"),
        Pais(nome=Portugues(portugues=Nome(common="Nepal")), capital=listOf("Kathmandu"), bandeira=FlagSvg(png=R.drawable.np), regiao="Asia", sigla="NP"),
        Pais(nome=Portugues(portugues=Nome(common="Terras Austrais e Antárticas Francesas")), capital=listOf("Port-aux-Français"), bandeira=FlagSvg(png=R.drawable.tf), regiao= "Antarctic", sigla="TF"),
        Pais(nome=Portugues(portugues=Nome(common="Ilha Formosa")), capital=listOf("Taipei"), bandeira=FlagSvg(png=R.drawable.tw), regiao="Asia", sigla="TW"),
        Pais(nome=Portugues(portugues=Nome(common="Benin")), capital=listOf("Porto-Novo"), bandeira=FlagSvg(png=R.drawable.bj), regiao="Africa", sigla="BJ"),
        Pais(nome=Portugues(portugues=Nome(common="Bulgária")), capital=listOf("Sofia"), bandeira=FlagSvg(png=R.drawable.bg), regiao="Europa", sigla="BG"),
        Pais(nome=Portugues(portugues=Nome(common="Moldávia")), capital=listOf("Chisinau"), bandeira=FlagSvg(png=R.drawable.md), regiao="Europa", sigla="MD"),
        Pais(nome=Portugues(portugues=Nome(common="Ilha de Man")), capital=listOf("Douglas"), bandeira=FlagSvg(png=R.drawable.im), regiao="Europa", sigla="IM"),
        Pais(nome=Portugues(portugues=Nome(common="Butão")), capital=listOf("Thimphu"), bandeira=FlagSvg(png=R.drawable.bt), regiao="Asia", sigla="BT"),
        Pais(nome=Portugues(portugues=Nome(common="Camboja")), capital=listOf("Phnom Penh"), bandeira=FlagSvg(png=R.drawable.kh), regiao="Asia", sigla="KH"),
        Pais(nome=Portugues(portugues=Nome(common="Antígua e Barbuda")), capital=listOf("São João"), bandeira=FlagSvg(png=R.drawable.ag), regiao="America do Norte e Central", sigla="AG"),
        Pais(nome=Portugues(portugues=Nome(common="Haiti")), capital=listOf("Port-au-Prince"), bandeira=FlagSvg(png=R.drawable.ht), regiao="America do Norte e Central", sigla="HT"),
        Pais(nome=Portugues(portugues=Nome(common="Cabo Verde")), capital=listOf("Praia"), bandeira=FlagSvg(png=R.drawable.cv), regiao="Africa", sigla="CV"),
        Pais(nome=Portugues(portugues=Nome(common="Geórgia")), capital=listOf("Tbilisi"), bandeira=FlagSvg(png=R.drawable.ge), regiao="Asia", sigla="GE"),
        Pais(nome=Portugues(portugues=Nome(common="Burundi")), capital=listOf("Gitega"), bandeira=FlagSvg(png=R.drawable.bi), regiao="Africa", sigla="BI"),
        Pais(nome=Portugues(portugues=Nome(common="Bahamas")), capital=listOf("Nassau"), bandeira=FlagSvg(png=R.drawable.bs), regiao="America do Norte e Central", sigla="BS"),
        Pais(nome=Portugues(portugues=Nome(common="Maurício")), capital=listOf("Port Louis"), bandeira=FlagSvg(png=R.drawable.mu), regiao="Africa", sigla="UM"),
        Pais(nome=Portugues(portugues=Nome(common="Líbia")), capital=listOf("Trípoli"), bandeira=FlagSvg(png=R.drawable.ly), regiao="Africa", sigla="LY"),
        Pais(nome=Portugues(portugues=Nome(common="Malawi")), capital=listOf("Lilongwe"), bandeira=FlagSvg(png=R.drawable.mw), regiao="Africa", sigla="MW"),
        Pais(nome=Portugues(portugues=Nome(common="México")), capital=listOf("Cidade do México"), bandeira=FlagSvg(png=R.drawable.mx), regiao="America do Norte e Central", sigla="MX"),
        Pais(nome=Portugues(portugues=Nome(common="Suazilândia")), capital=listOf("Mbabane"), bandeira=FlagSvg(png=R.drawable.sz), regiao="Africa", sigla="SZ"),
        Pais(nome=Portugues(portugues=Nome(common="Papua Nova Guiné")), capital=listOf("Port Moresby"), bandeira=FlagSvg(png=R.drawable.pg), regiao="Oceania", sigla="PG"),
        Pais(nome=Portugues(portugues=Nome(common="Dominica")), capital=listOf("Roseau"), bandeira=FlagSvg(png=R.drawable.dm), regiao="America do Norte e Central", sigla="DM"),
        Pais(nome=Portugues(portugues=Nome(common="Liechtenstein")), capital=listOf("Vaduz"), bandeira=FlagSvg(png=R.drawable.li), regiao="Europa", sigla="LI"),
        Pais(nome=Portugues(portugues=Nome(common="Rússia")), capital=listOf("Moscou"), bandeira=FlagSvg(png=R.drawable.ru), regiao="Europa", sigla="RU"),
        Pais(nome=Portugues(portugues=Nome(common="Israel")), capital=listOf("Jerusalém"), bandeira=FlagSvg(png=R.drawable.il), regiao="Asia", sigla="IL"),
        Pais(nome=Portugues(portugues=Nome(common="Singapura")), capital=listOf("Singapura"), bandeira=FlagSvg(png=R.drawable.sg), regiao="Asia", sigla="SG"),
        Pais(nome=Portugues(portugues=Nome(common="Uganda")), capital=listOf("Kampala"), bandeira=FlagSvg(png=R.drawable.ug),regiao="Africa", sigla="UG"),
        Pais(nome=Portugues(portugues=Nome(common="Eslováquia")), capital=listOf("Bratislava"), bandeira=FlagSvg(png=R.drawable.sk), regiao="Europa", sigla="SK"),
        Pais(nome=Portugues(portugues=Nome(common="Tonga")), capital=listOf("Nuku'alofa"), bandeira=FlagSvg(png=R.drawable.to), regiao="Oceania", sigla="TO"),
        Pais(nome=Portugues(portugues=Nome(common="Emirados Árabes Unidos")), capital=listOf("Abu Dhabi"), bandeira=FlagSvg(png=R.drawable.ae), regiao="Asia", sigla="EA"),
        Pais(nome=Portugues(portugues=Nome(common="Mayotte")), capital=listOf("Mamoudzou"), bandeira=FlagSvg(png=R.drawable.yt), regiao="Africa", sigla="YT"),
        Pais(nome=Portugues(portugues=Nome(common="Suriname")), capital=listOf("Paramaribo"), bandeira=FlagSvg(png=R.drawable.sr), regiao="America do Sul", sigla="SR"),
        Pais(nome=Portugues(portugues=Nome(common="Uzbequistão")), capital=listOf("Tashkent"), bandeira=FlagSvg(png=R.drawable.uz), regiao="Asia", sigla="UZ"),
        Pais(nome=Portugues(portugues=Nome(common="Arábia Saudita")), capital=listOf("Riyadh"), bandeira=FlagSvg(png=R.drawable.sa), regiao="Asia", sigla="SA"),
        Pais(nome=Portugues(portugues=Nome(common="Egito")), capital=listOf("Cairo"), bandeira=FlagSvg(png=R.drawable.eg), regiao="Africa", sigla="EG"),
        Pais(nome=Portugues(portugues=Nome(common="Itália")), capital=listOf("Roma"), bandeira=FlagSvg(png=R.drawable.it), regiao="Europa", sigla="IT"),
        Pais(nome=Portugues(portugues=Nome(common="Madagáscar")), capital=listOf("Antananarivo"), bandeira=FlagSvg(png=R.drawable.mg), regiao="Africa", sigla="MG"),
        Pais(nome=Portugues(portugues=Nome(common="Nova Caledónia")), capital=listOf("Nouméa"), bandeira=FlagSvg(png=R.drawable.nc), regiao="Oceania", sigla="NC"),
        Pais(nome=Portugues(portugues=Nome(common="Canadá")), capital=listOf("Ottawa"), bandeira=FlagSvg(png=R.drawable.ca), regiao="America do Norte e Central", sigla="CA"),
        Pais(nome=Portugues(portugues=Nome(common="Ilhas Virgens dos Estados Unidos")), capital=listOf("Charlotte Amalie"), bandeira=FlagSvg(png=R.drawable.vi), regiao="America do Norte e Central" , sigla="VI"),
        Pais(nome=Portugues(portugues=Nome(common="Ilhas Marshall")), capital=listOf("Majuro"), bandeira=FlagSvg(png=R.drawable.mh), regiao="Oceania", sigla="MS"),
        Pais(nome=Portugues(portugues=Nome(common="Mauritânia")), capital=listOf("Nouakchott"), bandeira=FlagSvg(png=R.drawable.mr), regiao="Africa", sigla="MR"),
        Pais(nome=Portugues(portugues=Nome(common="Gâmbia")), capital=listOf("Banjul"), bandeira=FlagSvg(png=R.drawable.gm), regiao="Africa", sigla="GM"),
        Pais(nome=Portugues(portugues=Nome(common="Trinidade e Tobago")), capital=listOf("Porto de Espanha"), bandeira=FlagSvg(png=R.drawable.tt), regiao="America do Sul", sigla="TT"),
        Pais(nome=Portugues(portugues=Nome(common="Seicheles")), capital=listOf("Victoria"), bandeira=FlagSvg(png=R.drawable.sc), regiao="Africa", sigla="SC"),
        Pais(nome=Portugues(portugues=Nome(common="Japão")), capital=listOf("Tóquio"), bandeira=FlagSvg(png=R.drawable.jp), regiao="Asia", sigla="JP"),
        Pais(nome=Portugues(portugues=Nome(common="Brasil")), capital=listOf("Brasília"), bandeira=FlagSvg(png=R.drawable.br), regiao="America do Sul", sigla="BR"),
        Pais(nome=Portugues(portugues=Nome(common="Síria")), capital=listOf("Damascus"), bandeira=FlagSvg(png=R.drawable.sy), regiao="Asia", sigla="SY"),
        Pais(nome=Portugues(portugues=Nome(common="Santa Helena, Ascensão e Tristão da Cunha")), capital=listOf("Jamestown"), bandeira=FlagSvg(png=R.drawable.sh), regiao=" Africa", sigla="SH"),
        Pais(nome=Portugues(portugues=Nome(common="Tanzânia")), capital=listOf("Dodoma"), bandeira=FlagSvg(png=R.drawable.tz), regiao="Africa", sigla="TZ"),
        Pais(nome=Portugues(portugues=Nome(common="Andorra")), capital=listOf("Andorra-a-Velha"), bandeira=FlagSvg(png=R.drawable.ad), regiao="Europa", sigla="AD"),
        Pais(nome=Portugues(portugues=Nome(common="Irão")), capital=listOf("Teerã"), bandeira=FlagSvg(png=R.drawable.ir), regiao="Asia", sigla="IR"),
        Pais(nome=Portugues(portugues=Nome(common="Togo")), capital=listOf("Lomé"), bandeira=FlagSvg(png=R.drawable.tg), regiao="Africa", sigla="TG"),
        Pais(nome=Portugues(portugues=Nome(common="Malta")), capital=listOf("Valletta"), bandeira=FlagSvg(png=R.drawable.mt), regiao="Europa", sigla="MT"),
        Pais(nome=Portugues(portugues=Nome(common="Coreia do Sul")), capital=listOf("Seul"), bandeira=FlagSvg(png=R.drawable.kr), regiao="Asia", sigla="KR"),
        Pais(nome=Portugues(portugues=Nome(common="Samoa")), capital=listOf("Apia"), bandeira=FlagSvg(png=R.drawable.ws), regiao="Oceania", sigla="WS"),
        Pais(nome=Portugues(portugues=Nome(common="Alemanha")), capital=listOf("Berlim"), bandeira=FlagSvg(png=R.drawable.de), regiao="Europa", sigla="DE"),
        Pais(nome=Portugues(portugues=Nome(common="Níger")), capital=listOf("Niamey"), bandeira=FlagSvg(png=R.drawable.ne), regiao="Africa", sigla="NE"),
        Pais(nome=Portugues(portugues=Nome(common="Jamaica")), capital=listOf("Kingston"), bandeira=FlagSvg(png=R.drawable.jm), regiao="America do Norte e Central", sigla="JM"),
        Pais(nome=Portugues(portugues=Nome(common="Nicarágua")), capital=listOf("Manágua"), bandeira=FlagSvg(png=R.drawable.ni), regiao="America do Norte e Central", sigla="NI"),
        Pais(nome=Portugues(portugues=Nome(common="Guiné")), capital=listOf("Conacri"), bandeira=FlagSvg(png=R.drawable.gn), regiao="Africa", sigla="GN"),
        Pais(nome=Portugues(portugues=Nome(common="Anguilla")), capital=listOf("O Vale"), bandeira=FlagSvg(png=R.drawable.ai), regiao="America do Norte e Central", sigla="IA"),
        Pais(nome=Portugues(portugues=Nome(common="Alândia")), capital=listOf("Mariehamn"), bandeira=FlagSvg(png=R.drawable.ax), regiao="Europa", sigla="AX"),
        Pais(nome=Portugues(portugues=Nome(common="Bélgica")), capital=listOf("Bruxelas"), bandeira=FlagSvg(png=R.drawable.be), regiao="Europa", sigla="BE"),
        Pais(nome=Portugues(portugues=Nome(common="Portugal")), capital=listOf("Lisboa"), bandeira=FlagSvg(png=R.drawable.pt), regiao="Europa", sigla="PT"),
        Pais(nome=Portugues(portugues=Nome(common="Dinamarca")), capital=listOf("Copenhague"), bandeira=FlagSvg(png=R.drawable.dk), regiao="Europa", sigla="DK"),
        Pais(nome=Portugues(portugues=Nome(common="Filipinas")), capital=listOf("Manila"), bandeira=FlagSvg(png=R.drawable.ph), regiao="Asia", sigla="PH"),
        Pais(nome=Portugues(portugues=Nome(common="Wallis e Futuna")), capital=listOf("Mata-Utu"), bandeira=FlagSvg(png=R.drawable.wf), regiao="Oceania", sigla="WF"),
        Pais(nome=Portugues(portugues=Nome(common="Áustria")), capital=listOf("Viena"), bandeira=FlagSvg(png=R.drawable.at), regiao="Europa", sigla="AT"),
        Pais(nome=Portugues(portugues=Nome(common="Guiné-Bissau")), capital=listOf("Bissau"), bandeira=FlagSvg(png=R.drawable.gw), regiao="Africa", sigla="GW"),
        Pais(nome=Portugues(portugues=Nome(common="Mónaco")), capital=listOf("Monaco"), bandeira=FlagSvg(png=R.drawable.mc), regiao="Europa", sigla="MC"),
        Pais(nome=Portugues(portugues=Nome(common="Namíbia")), capital=listOf("Windhoek"), bandeira=FlagSvg(png=R.drawable.na), regiao="Africa", sigla="NA"),
        Pais(nome=Portugues(portugues=Nome(common="Ilhas Menores Distantes dos Estados Unidos")), capital=listOf("Washington DC"), bandeira=FlagSvg(png=R.drawable.um), regiao="America do Norte e Central ", sigla="UM"),
        Pais(nome=Portugues(portugues=Nome(common="Costa Rica")), capital=listOf("San José"), bandeira=FlagSvg(png=R.drawable.cr), regiao="America do Norte e Central", sigla="CR"),
        Pais(nome=Portugues(portugues=Nome(common="Bósnia e Herzegovina")), capital=listOf("Sarajevo"), bandeira=FlagSvg(png=R.drawable.ba), regiao="Europa", sigla="BA"),
        Pais(nome=Portugues(portugues=Nome(common="Moçambique")), capital=listOf("Maputo"), bandeira=FlagSvg(png=R.drawable.mz), regiao="Africa", sigla="MZ"),
        Pais(nome=Portugues(portugues=Nome(common="Reunião")), capital=listOf("Saint-Denis"), bandeira=FlagSvg(png=R.drawable.re), regiao="Africa", sigla="RÉ"),
        Pais(nome=Portugues(portugues=Nome(common="Montenegro")), capital=listOf("Podgorica"), bandeira=FlagSvg(png=R.drawable.me), regiao="Europa", sigla="ME"),
        Pais(nome=Portugues(portugues=Nome(common="Coreia do Norte")), capital=listOf("Pyongyang"), bandeira=FlagSvg(png=R.drawable.kp), regiao="Asia", sigla="KP"),
        Pais(nome=Portugues(portugues=Nome(common="Marianas Setentrionais")), capital=listOf("Saipan"), bandeira=FlagSvg(png=R.drawable.mp), regiao="Oceania", sigla="MP"),
        Pais(nome=Portugues(portugues=Nome(common="Ucrânia")), capital=listOf("Kiev"), bandeira=FlagSvg(png=R.drawable.ua), regiao="Europa", sigla="UA"),
        Pais(nome=Portugues(portugues=Nome(common="Iraque")), capital=listOf("Bagdá"), bandeira=FlagSvg(png=R.drawable.iq), regiao="Asia", sigla="IQ"),
        Pais(nome=Portugues(portugues=Nome(common="Ilhas Geórgia do Sul e Sandwich do Sul")), capital=listOf("King Edward Point"), bandeira=FlagSvg(png=R.drawable.gs), regiao ="Antarctic", sigla="GS"),
        Pais(nome=Portugues(portugues=Nome(common="Angola")), capital=listOf("Luanda"), bandeira=FlagSvg(png=R.drawable.ao), regiao="Africa", sigla="AO"),
        Pais(nome=Portugues(portugues=Nome(common="Serra Leoa")), capital=listOf("Freetown"), bandeira=FlagSvg(png=R.drawable.sl), regiao="Africa", sigla="SL"),
        Pais(nome=Portugues(portugues=Nome(common="Micronésia")), capital=listOf("Palikir"), bandeira=FlagSvg(png=R.drawable.fm), regiao="Oceania", sigla="FM"),
        Pais(nome=Portugues(portugues=Nome(common="Cuba")), capital=listOf("Havana"), bandeira=FlagSvg(png=R.drawable.cu), regiao="America do Norte e Central", sigla="CU"),
        Pais(nome=Portugues(portugues=Nome(common="Ilhas Turks e Caicos")), capital=listOf("Cockburn Town"), bandeira=FlagSvg(png=R.drawable.tc), regiao="America do Norte e Central", sigla="TC"),
        Pais(nome=Portugues(portugues=Nome(common="Sérvia")), capital=listOf("Belgrado"), bandeira=FlagSvg(png=R.drawable.rs), regiao="Europa", sigla="RS"),
        Pais(nome=Portugues(portugues=Nome(common="Equador")), capital=listOf("Quito"), bandeira=FlagSvg(png=R.drawable.ec), regiao="America do Sul", sigla="EC"),
        Pais(nome=Portugues(portugues=Nome(common="Ilhas Faroé")), capital=listOf("Tórshavn"), bandeira=FlagSvg(png=R.drawable.fo), regiao="Europa", sigla="FO"),
        Pais(nome=Portugues(portugues=Nome(common="Palestina")), capital=listOf("Ramallah, Jerusalém"), bandeira=FlagSvg(png=R.drawable.ps), regiao="Asia", sigla="PS"),
        Pais(nome=Portugues(portugues=Nome(common="Turquia")), capital=listOf("Ankara"), bandeira=FlagSvg(png=R.drawable.tr), regiao="Asia", sigla="TR"),
        Pais(nome=Portugues(portugues=Nome(common="Kiribati")), capital=listOf("South Tarawa"), bandeira=FlagSvg(png=R.drawable.ki), regiao="Oceania", sigla="KI"),
        Pais(nome=Portugues(portugues=Nome(common="Cazaquistão")), capital=listOf("Nur-Sultan"), bandeira=FlagSvg(png=R.drawable.kz), regiao="Asia", sigla="KZ"),
        Pais(nome=Portugues(portugues=Nome(common="Gibraltar")), capital=listOf("Gibraltar"), bandeira=FlagSvg(png=R.drawable.gi), regiao="Europa", sigla="GI"),
        Pais(nome=Portugues(portugues=Nome(common="Islândia")), capital=listOf("Reiquiavique"), bandeira=FlagSvg(png=R.drawable.`is`), regiao="Europa", sigla="IS"),
        Pais(nome=Portugues(portugues=Nome(common="Palau")), capital=listOf("Ngerulmud"), bandeira=FlagSvg(png=R.drawable.pw), regiao="Oceania", sigla="PW"),
        Pais(nome=Portugues(portugues=Nome(common="Catar")), capital=listOf("Doha"), bandeira=FlagSvg(png=R.drawable.qa), regiao="Asia", sigla="QA"),
        Pais(nome=Portugues(portugues=Nome(common="Suíça")), capital=listOf("Berna"), bandeira=FlagSvg(png=R.drawable.ch), regiao="Europa", sigla="CH"),
        Pais(nome=Portugues(portugues=Nome(common="Polinésia Francesa")), capital=listOf("Papeetē"), bandeira=FlagSvg(png=R.drawable.pf), regiao="Oceania", sigla="PF"),
        Pais(nome=Portugues(portugues=Nome(common="Ilhas Pitcairn")), capital=listOf("Adamstown"), bandeira=FlagSvg(png=R.drawable.pn), regiao="Oceania", sigla="NP"),
        Pais(nome=Portugues(portugues=Nome(common="Jordânia")), capital=listOf("Amã"), bandeira=FlagSvg(png=R.drawable.jo), regiao="Asia", sigla="JO"),
        Pais(nome=Portugues(portugues=Nome(common="Myanmar")), capital=listOf("Nepiedó"), bandeira=FlagSvg(png=R.drawable.mm), regiao="Asia", sigla="MM"),
        Pais(nome=Portugues(portugues=Nome(common="Tailândia")), capital=listOf("Bangkok"), bandeira=FlagSvg(png=R.drawable.th), regiao="Asia", sigla="TH"),
        Pais(nome=Portugues(portugues=Nome(common="Países Baixos Caribenhos")), capital=listOf("Kralendijk"), bandeira=FlagSvg(png=R.drawable.bq), regiao="America do Norte e Central", sigla="QQ"),
        Pais(nome=Portugues(portugues=Nome(common="Aruba")), capital=listOf("Oranjestad"), bandeira=FlagSvg(png=R.drawable.aw), regiao="America do Norte e Central", sigla="AW"),
        Pais(nome=Portugues(portugues=Nome(common="Guadalupe")), capital=listOf("Basse-Terre"), bandeira=FlagSvg(png=R.drawable.gp), regiao="America do Norte e Central", sigla="GP"),
        Pais(nome=Portugues(portugues=Nome(common="Nigéria")), capital=listOf("Abuja"), bandeira=FlagSvg(png=R.drawable.ng), regiao="Africa", sigla="NG"),
        Pais(nome=Portugues(portugues=Nome(common="Bahrein")), capital=listOf("Manama"), bandeira=FlagSvg(png=R.drawable.bh), regiao="Asia", sigla="BH"),
        Pais(nome=Portugues(portugues=Nome(common="Laos")), capital=listOf("Vientiane"), bandeira=FlagSvg(png=R.drawable.la), regiao="Asia", sigla="LA"),
        Pais(nome=Portugues(portugues=Nome(common="Ilhas Cocos (Keeling)")), capital=listOf("West Island"), bandeira=FlagSvg(png=R.drawable.cc), regiao="Oceania" , sigla="CC"),
        Pais(nome=Portugues(portugues=Nome(common="Djibouti")), capital=listOf("Djibouti"), bandeira=FlagSvg(png=R.drawable.dj), regiao="Africa", sigla="DJ"),
        Pais(nome=Portugues(portugues=Nome(common="Ilhas Salomão")), capital=listOf("Honiara"), bandeira=FlagSvg(png=R.drawable.sb), regiao="Oceania", sigla="SB"),
        Pais(nome=Portugues(portugues=Nome(common="Índia")), capital=listOf("New Delhi"), bandeira=FlagSvg(png=R.drawable.`in`), regiao="Asia", sigla="EM"),
        Pais(nome=Portugues(portugues=Nome(common="San Marino")), capital=listOf("Cidade de San Marino"), bandeira=FlagSvg(png=R.drawable.sm), regiao="Europa", sigla="SM"),
        Pais(nome=Portugues(portugues=Nome(common="Luxemburgo")), capital=listOf("Luxemburgo"), bandeira=FlagSvg(png=R.drawable.lu), regiao="Europa", sigla="LU"),
        Pais(nome=Portugues(portugues=Nome(common="São Martinho")), capital=listOf("Philipsburg"), bandeira=FlagSvg(png=R.drawable.sx), regiao="America do Norte e Central", sigla="SX"),
        Pais(nome=Portugues(portugues=Nome(common="Ilhas Malvinas")), capital=listOf("Stanley"), bandeira=FlagSvg(png=R.drawable.fk), regiao="America do Norte e Central", sigla="FC"),
        Pais(nome=Portugues(portugues=Nome(common="República Centro-Africana")), capital=listOf("Bangui"), bandeira=FlagSvg(png=R.drawable.cf), regiao="Africa", sigla="CF"),
        Pais(nome=Portugues(portugues=Nome(common="Botswana")), capital=listOf("Gaborone"), bandeira=FlagSvg(png=R.drawable.bw), regiao="Africa", sigla="BW"),
        Pais(nome=Portugues(portugues=Nome(common="ilha da Curação")), capital=listOf("Willemstad"), bandeira=FlagSvg(png=R.drawable.cw), regiao="America do Norte e Central", sigla="CW"),
        Pais(nome=Portugues(portugues=Nome(common="Guernsey")), capital=listOf("St. Peter Port"), bandeira=FlagSvg(png=R.drawable.gg), regiao="Europa", sigla="GG"),
        Pais(nome=Portugues(portugues=Nome(common="Noruega")), capital=listOf("Oslo"), bandeira=FlagSvg(png=R.drawable.no), regiao="Europa", sigla="NO"),
        Pais(nome=Portugues(portugues=Nome(common="Gabão")), capital=listOf("Libreville"), bandeira=FlagSvg(png=R.drawable.ga), regiao="Africa", sigla="GA"),
        Pais(nome=Portugues(portugues=Nome(common="Zimbabwe")), capital=listOf("Harare"), bandeira=FlagSvg(png=R.drawable.zw), regiao="Africa", sigla="ZW"),
        Pais(nome=Portugues(portugues=Nome(common="Lesoto")), capital=listOf("Maseru"), bandeira=FlagSvg(png=R.drawable.ls), regiao="Africa", sigla="LS"),
        Pais(nome=Portugues(portugues=Nome(common="Eslovénia")), capital=listOf("Liubliana"), bandeira=FlagSvg(png=R.drawable.si), regiao="Europa", sigla="SI"),
        Pais(nome=Portugues(portugues=Nome(common="Argentina")), capital=listOf("Buenos Aires"), bandeira=FlagSvg(png=R.drawable.ar), regiao="America do Sul", sigla="AR"),
        Pais(nome=Portugues(portugues=Nome(common="Burkina Faso")), capital=listOf("Uagadugu"), bandeira=FlagSvg(png=R.drawable.bf), regiao="Africa", sigla="bf"),
        Pais(nome=Portugues(portugues=Nome(common="Iémen")), capital=listOf("Saná"), bandeira=FlagSvg(png=R.drawable.ye), regiao="Asia", sigla="YE"),
        Pais(nome=Portugues(portugues=Nome(common="República Democrática do Congo")), capital=listOf("Quinxassa"), bandeira=FlagSvg(png=R.drawable.cd), regiao="Africa", sigla="CD"),
        Pais(nome=Portugues(portugues=Nome(common="Omã")), capital=listOf("Muscat"), bandeira=FlagSvg(png=R.drawable.om), regiao="Asia", sigla="OM"),
        Pais(nome=Portugues(portugues=Nome(common="Indonésia")), capital=listOf("Jacarta"), bandeira=FlagSvg(png=R.drawable.id), regiao="Asia", sigla="ID"),
        Pais(nome=Portugues(portugues=Nome(common="Nauru")), capital=listOf("Iarém"), bandeira=FlagSvg(png=R.drawable.nr), regiao="Oceania", sigla="NR"),
        Pais(nome=Portugues(portugues=Nome(common="Ruanda")), capital=listOf("Quigali"), bandeira=FlagSvg(png=R.drawable.rw), regiao="Africa", sigla="RW"),
        Pais(nome=Portugues(portugues=Nome(common="Macedónia do Norte")), capital=listOf("Escópia"), bandeira=FlagSvg(png=R.drawable.mk), regiao="Europa", sigla="MK"),
        Pais(nome=Portugues(portugues=Nome(common="Kosovo")), capital=listOf("Pristina"), bandeira=FlagSvg(png=R.drawable.xk), regiao="Europa", sigla="XK"),
        Pais(nome=Portugues(portugues=Nome(common="Holanda")), capital=listOf("Amsterdam"), bandeira=FlagSvg(png=R.drawable.nl), regiao="Europa", sigla="NL"),
        Pais(nome=Portugues(portugues=Nome(common="Tunísia")), capital=listOf("Tunis"), bandeira=FlagSvg(png=R.drawable.tn), regiao="Africa", sigla="TN"),
        Pais(nome=Portugues(portugues=Nome(common="Sudão do Sul")), capital=listOf("Juba"), bandeira=FlagSvg(png=R.drawable.ss), regiao="Africa", sigla="SS"),
        Pais(nome=Portugues(portugues=Nome(common="Honduras")), capital=listOf("Tegucigalpa"), bandeira=FlagSvg(png=R.drawable.hn), regiao="America do Norte e Central", sigla="HN"),
        Pais(nome=Portugues(portugues=Nome(common="São Vicente e Granadinas")), capital=listOf("Kingstown"), bandeira=FlagSvg(png=R.drawable.vc), regiao="America do Norte e Central", sigla="VC"),
        Pais(nome=Portugues(portugues=Nome(common="Sri Lanka")), capital=listOf("Sri Jayawardenepura Kotte"), bandeira=FlagSvg(png=R.drawable.lk), regiao="Asia", sigla="LK"),
        Pais(nome=Portugues(portugues=Nome(common="Hong Kong")), capital=listOf("Cidade de Victoria"), bandeira=FlagSvg(png=R.drawable.hk), regiao="Asia", sigla="HK")
    )
}

fun getPaisByContinente(continente: String): List<Pais> {
    return getAllPaises().filter {
        it.regiao.startsWith(continente, ignoreCase = true)
    }
}

fun getPaisByCountry(continente: String): List<Pais> {
    return getAllPaises().filter {
        it.nome.portugues.common.startsWith(continente, ignoreCase = true)
    }
}

fun getAllContinentesString(): List<String> {
return listOf("África", "America do norte e Central", "America do Sul", "Ásia", "Europa", "Oceania")
}
